"""Constants for the reverso integration."""

DOMAIN = "reversotts"
CONF_PITCH = "pitch"
CONF_BITRATE = "bitrate"
DEFAULT_LANG = "Sharon-US-English"
DEFAULT_PITCH = "100"
DEFAULT_BITRATE = "128k"
SUPPORT_OPTIONS = ["pitch", "bitrate"]
BITRATE_OPTIONS = ["22k", "96k", "128k", "192k", "320k"]

SUPPORT_LANGUAGES = [
    "Leila-Arabic",
    "Mehdi-Arabic",
    "Nizar-Arabic",
    "Salma-Arabic",
    "Lisa-Australian-English",
    "Tyler-Australian-English",
    "Jeroen-Belgian-Dutch",
    "Sofie-Belgian-Dutch",
    "Zoe-Belgian-Dutch",
    "Alice-BE-Belgian-French",
    "Anais-BE-Belgian-French",
    "Antoine-BE-Belgian-French",
    "Bruno-BE-Belgian-French",
    "Claire-BE-Belgian-French",
    "Julie-BE-Belgian-French",
    "Justine-Belgian-French",
    "Manon-BE-Belgian-French",
    "Margaux-BE-Belgian-French",
    "Marcia-Brazilian",
    "Graham-British",
    "Lucy-British",
    "Peter-British",
    "QueenElizabeth-British",
    "Rachel-British",
    "Louise-Canadian-French",
    "Laia-Catalan",
    "Eliska-Czech",
    "Mette-Danish",
    "Rasmus-Danish",
    "Daan-Dutch",
    "Femke-Dutch",
    "Jasmijn-Dutch",
    "Max-Dutch",
    "Samuel-Finland-Swedish",
    "Sanna-Finnish",
    "Alice-French",
    "Anais-French",
    "Antoine-French",
    "Bruno-French",
    "Claire-French",
    "Julie-French",
    "Manon-French",
    "Margaux-French",
    "Andreas-German",
    "Claudia-German",
    "Julia-German",
    "Klaus-German",
    "Sarah-German",
    "Kal-Gothenburg-Swedish",
    "Dimitris-Greek",
    "he-IL-Asaf-Hebrew",
    "Deepa-Indian-English",
    "Chiara-Italian",
    "Fabiana-Italian",
    "Vittorio-Italian",
    "Sakura-Japanese",
    "Minji-Korean",
    "Lulu-Mandarin-Chinese",
    "Bente-Norwegian",
    "Kari-Norwegian",
    "Olav-Norwegian",
    "Ania-Polish",
    "Monika-Polish",
    "Celia-Portuguese",
    "ro-RO-Andrei-Romanian",
    "Alyona-Russian",
    "Mia-Scanian",
    "Antonio-Spanish",
    "Ines-Spanish",
    "Maria-Spanish",
    "Elin-Swedish",
    "Emil-Swedish",
    "Emma-Swedish",
    "Erik-Swedish",
    "Ipek-Turkish",
    "Heather-US-English",
    "Karen-US-English",
    "Kenny-US-English",
    "Laura-US-English",
    "Micah-US-English",
    "Nelly-US-English",
    "Rod-US-English",
    "Ryan-US-English",
    "Saul-US-English",
    "Sharon-US-English",
    "Tracy-US-English",
    "Will-US-English",
    "Rodrigo-US-Spanish",
    "Rosa-US-Spanish",
]
